# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0a32dd66f6f402d7412d2d799fc51a64"
application_url = "https://camp-stylus-slight-popularity.trycloudflare.com"
embedded = true
name = "keltestshop"
handle = "keltestshop"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://camp-stylus-slight-popularity.trycloudflare.com/auth/callback",
  "https://camp-stylus-slight-popularity.trycloudflare.com/auth/shopify/callback",
  "https://camp-stylus-slight-popularity.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
